### ISSUE TITLE
Bugs sur les sous

### ISSUE THREAD

**Issue by GatitoStudioAPIAccount** [GatitoStudio/CryptoInc#144]
Les achats ne fonctionnent pas, le minage auto est bloqué (ne fonctionne pas) et ce que j'ai obtenu en ouvrant l'application ne correspond pas à ce que j'aurai dû avoir avec le minage auto....

**Comment by GatitoStudio** [comment]
les achats fonctionnes et c'est normal c'est 5% du rendement total. Je ferme
